cdoapi.py, cmor_source.py, cmor_target.py, cmor_utils.py, ece2cmorlib.py, ifs2cmor.py, jsonloader.py, nemo2cmor.py, postproc.py, resources/ifspar.json
Other masks can be trivially inserted by editing the ifspar.json file.
=> Added (land) mask for IFS

cdoapi.py, postproc.py, resources/ifspar.json
=> Added tsl from merging levels

environment.yml
The auto tests are also successful, like my local test. Thus issue solved
=> Fixing the dependency on the wheel 0.30.0 package version #102

ece2cmor3/resources/ifspar.json
Added tendencies and some missing variables to ifspar.json, moved all new derived variables to table 129.
=> Ifspar upgrade

ece2cmor3/ece2cmor.py, ece2cmor3/ece2cmorlib.py, ece2cmor3/ifs2cmor.py
Using multiple processes for parallel cmorization of IFS output, avoiding GIL problems
=> Parallel cmor

ece2cmor3/cmor_utils.py, ece2cmor3/ifs2cmor.py, ece2cmor3/nemo2cmor.py, ece2cmor3/resources/ifspar.json
Made unit conversions allow a constant term to include degree celsius to/from Kelvin conversions
=> Degc2Kconv

ece2cmor3/nemo2cmor.py
Fixed nemo single-point variables
=> Attempt to fix nemo 1point variables

ece2cmor3/cmor_utils.py, ece2cmor3/nemo2cmor.py
=> Nemo ofx fix

ece2cmor3/cmor_target.py, ece2cmor3/nemo2cmor.py, test/nemo2cmor_test.py
Fixed (ocean) extra dimensions appearing as horizontal spatial dimensions, and the meridional variables.
=> Nemo gridfixes

ece2cmor3/components.py, ece2cmor3/resources/ifspar.json, ece2cmor3/taskloader.py
Added ocean and sea-ice realms to ifs so that siconca can be created from ifs output. Changed the tos table in ifspar.json to "none" so it is never used currently.
=> Ifs realms

ece2cmor3/cmor_utils.py, ece2cmor3/ece2cmor.py, ece2cmor3/ece2cmorlib.py, ece2cmor3/grib_filter.py, ece2cmor3/ifs2cmor.py, ece2cmor3/postproc.py
Added option to dismiss 2D grid for IFS.
=> Ifs grid1d

env-osx-64.yml, environment.yml
=> Cmor release 3.3.3 december

env-osx-64.yml, environment.yml
Update the cmor library to b=version 3.4.0, see #636 and solving https://github.com/EC-Earth/ece2cmor3/issues/346#issuecomment-453025695
=> Cmor release 3.4.0

env-osx-64.yml, environment.yml
=> Conda forge cmor 3.4.0

ece2cmor3/cmor_utils.py, test/ifs2cmor_test.py, test/test_utils.py
As agreed, the averages in the 3- and 6-hourly tables have resp. bound 0,3,6,... and 0,6,12,... and the time stamps will be the midpoints of these bounds.
=> Fixed time bounds for sub-daily averages

ece2cmor3/components.py, ece2cmor3/ece2cmor.py, ece2cmor3/scripts/check-for-obsolete-cmor-variables-in-json-file.py, ece2cmor3/scripts/checkvars.py, ece2cmor3/scripts/create-nemo-only-list/create-nemo-only-list.sh, ece2cmor3/scripts/determine-missing-variables.sh
=> Issue 396 component names

ece2cmor3/nemo2cmor.py
Fixed the mapping of vertical ocean axes. IMPORTANT: ece2cmor3 assumes different axes have different long_name attributes in the raw model output.
=> Labeling z-axes by nc variable long name for uniqueness

ece2cmor3/cmor_target.py, ece2cmor3/nemo2cmor.py, test/cmor_target_test.py
Fixed ece2cmor3 messing up instantaneous and averaged time axes in same netcdf file
=> Nemo time axes

ece2cmor3/cmor_utils.py, ece2cmor3/nemo2cmor.py, ece2cmor3/resources/nemopar.json
Added Ofx deptho cmorization from bathy_meter.nc
=> Deptho bathy

ece2cmor3/cmor_source.py, ece2cmor3/ifs2cmor.py, ece2cmor3/postproc.py, ece2cmor3/resources/ifspar.json, test/cmor_source_test.py, test/postproc_test.py
Improved parsing of post-processing cdo expressions, corrected rsdscs and rsuscs.
=> Rscs correction

ece2cmor3/ifs2cmor.py
Make ifs2cmor able to cmorize instantaneous 3D model level fields using the "ps1" surface pressure formula term
=> Zfactor time1

ece2cmor3/nemo2cmor.py
=> Nemo time units

ece2cmor3/cmor_utils.py, ece2cmor3/ece2cmor.py
=> Added code to support custom parameter tables

ece2cmor3/grib_filter.py
=> Attempt to fix height level spectral fields

ece2cmor3/ece2cmorlib.py, ece2cmor3/ifs2cmor.py, ece2cmor3/lpjg2cmor.py, ece2cmor3/nemo2cmor.py, ece2cmor3/scripts/submit-script-examples/submit-at-bull-ece2cmor-leg-job-piControl.sh, ece2cmor3/tm52cmor.py, test/nemo2cmor_test.py
=> Single calendar

ece2cmor3/nemo2cmor.py, ece2cmor3/resources/nemopar.json
=> Deptho mask fix

ece2cmor3/ifs2cmor.py
Fixing the longitude eastward shift BUG in ece2cmor3 #553
=> Fixed incorrect shift in grid longitudes for IFS

ece2cmor3/cmor_utils.py, ece2cmor3/ece2cmorlib.py, ece2cmor3/tm52cmor.py
I removed grid-definition and renamed some variables for Lon and Lat (using array representation as default already earlier) as per request in #565. Also made some other cleaning up. Code works as before, but has few more checks and more robust file search for AerChemMIP output from TM5. 
I added also google-style docstrings into functions.
=> Cleanup tm5

ece2cmor3/grib_filter.py, ece2cmor3/ifs2cmor.py
Removed restriction to have spectral files for ifs2cmor3
=> Removed check for gridpoint and spectral file matching.

ece2cmor3/resources/ifspar.json
=> Correct upwelling aerosol-free SW fluxes

ece2cmor3/cdoapi.py, ece2cmor3/ece2cmorlib.py, ece2cmor3/ifs2cmor.py, ece2cmor3/postproc.py
=> Added areacella cmorization based upon 129 in ICMGG+000000 (just like orog)

ece2cmor3/grib_filter.py, ece2cmor3/ifs2cmor.py, ece2cmor3/postproc.py
Fixing last `hfdsl` issue in #594.
=> Flux inst bugfix

ece2cmor3/resources/lpjg-grid-content/create_cdo_ingrid_for_lpjgout.py
=> Lpjg ingrid python3 version

ece2cmor3/grib_file.py, ece2cmor3/grib_filter.py
Improved efficiency of grib filter and removed memory leaks slowing the filtering down on several systems.
=> Filter fast forward

ece2cmor3/grib_filter.py
…disappearing at 0 AM. Added fast-forwarding to january and december filtering code as well.
=> Fixed issue with fast-forward cache and model level variables 

ece2cmor3/grib_filter.py
Fixed mapping of 2D PEXTRA fields for COSP to the pressure-level fields in the data request
=> Cosp filter fix

ece2cmor3/grib_filter.py
=> Made grib filter more robust against duplicate records

ece2cmor3/lpjg2cmor.py
LPJG output variables with dimension soil-depth.
This fix will work in the future and will be downward-compatible.
=> Implemented a fix for downward-compatibility for changed

ece2cmor3/scripts/modify-metadata-template.sh
Accidentally pushed a new branch for this small change (I was still locally in the previous branch). Last tweak for #825.
=> Set co2box grid metadata to what has been used so far in optimesm #825.

environment.yml
=> Add via a pip install the CMIP7 data request api #858.
